let pokemonList = [
  {
    name: "seel",
    height: 3.07,
    weight: 198.4,
    category: "seaLion",
    abilities: ["thickFat", "hydration"],
    types: ["water"],
    weaknesses: ["grass", "electric"],
  },
  {
    name: "mamoswine",
    height: 8.02,
    weight: 641.5,
    category: "twinTusk",
    abilities: ["oblivious", "snowCloak"],
    types: ["ice", "ground"],
    weaknesses: ["steel", "fire", "grass", "water", "fighting"],
  },
  {
    name: "whiscash",
    height: 2.11,
    weight: 52.0,
    category: "whiskers",
    abilities: ["oblivious", "anticipation"],
    types: ["water", "ground"],
    weaknesses: ["grass"],
  },
  {
    name: "camerupt",
    height: 6.03,
    weight: 485.0,
    category: "eruption",
    abilities: ["magmaArmor", "solidRock"],
    types: ["fire", "ground"],
    weaknesses: ["water", "ground"],
  },
  {
    name: "slaking",
    height: 6.07,
    weight: 287.7,
    category: "lazy",
    abilities: ["truant"],
    types: ["normal"],
    weaknesses: ["fighting"],
  },
  {
    name: "poochyena",
    height: 1.08,
    weight: 30.0,
    category: "bite",
    abilities: ["runAway", "quickFeet"],
    types: ["dark"],
    weaknesses: ["fairy", "bug", "fighting"],
  },
  {
    name: "rillaboom",
    height: 6.11,
    weight: 198.4,
    category: "drummer",
    abilities: ["overgrow"],
    types: ["grass"],
    weaknesses: ["fire", "flying", "ice", "poison", "bug"],
  },
];
